### ISSUE TITLE
[bug] zsh: exec format error on MacOS 12.0.1

### ISSUE THREAD

**Issue by psenakv** [Gadiguibou/stdrename#22]
Following installation instruction, after trying to run, the output is only "zsh: exec format error".

**Comment by Gadiguibou** [comment]
Hi @psenakv! Thanks for the report!

That's a weird bug you're getting. Did you install stdrename using the instructions for a manual installation or using the instructions for cargo?

**Comment by psenakv** [comment]
Hey, sorry for late reply. I used both - first manual, then cargo. On manual, I got the error, with cargo, it worked seamlessly.

**Comment by Gadiguibou** [comment]
Thanks for the follow-up!

The binary released under the name `stdrename` is a GNU/Linux x86_64 binary. This explains the weird bug that you got when trying to execute it. I'm going to rename the binary so it's more obvious which binary targets which platform and edit the confusing sentence in the README.

I currently did not release a macOS binary since I don't have access to a Mac. Do you want to contribute one?

If you want to do so, you can follow these steps:

1. Clone this git repository into your directory of choice using `git clone git@github.com:Gadiguibou/stdrename.git` from your terminal or by downloading and extracting the zip file from [here](https://github.com/Gadiguibou/stdrename/archive/refs/heads/master.zip).
2. From your terminal, `cd` into the directory. For example: `cd stdrename`.
3. Compile the binary executable using `cargo build --release`.
4. Drag and drop the file named `stdrename` from `stdrename/target/release` into a GitHub comment on this issue.
5. Let me know whether you use an Intel or an Apple silicon (M1) Mac!

**Comment by psenakv** [comment]
Hey, I use Intel Mac. I zipped it 'cause GitHub don't allow binary files...
[stdrename.zip](https://github.com/Gadiguibou/stdrename/files/7675992/stdrename.zip)
